export const siteConfig = {
  name: "ImageUtils - Free Online Image Tools",
  description: "Professional AI-powered image tools for background removal, HEIC conversion, PDF creation, and text effects. Free online image processing tools.",
  url: process.env.NEXT_PUBLIC_BASE_URL || "https://imgutils.xyz",
  ogImage: "/og-image.jpg",
  keywords: [
    "AI image editing",
    "AI image editing tools",
    "background removal",
    "background removal tools",
    "text behind effect",
    "text behind effect tools",
    "image processing",
    "image processing tools",
    "AI tools",
    "AI tools online",
    "AI tools online free",
    "photo editing",
    "photo editing tools",
    "creative design",
    "creative design tools",
    "image background remover",
    "image background remover tools",
    "text effects",
    "text effects tools",
    "image manipulation",
    "image manipulation tools",
    "AI image editor",
    "AI image tools",
    "AI image background remover",
    "AI image text effects",
    "AI image manipulation",
    "AI image background generator",
    "AI image background changer",
    "AI image background editor",
    "AI image background remover",
    "AI image background remover online",
    "AI image background remover free",
    "AI image background remover online free",
    "image to pdf converter",
    "heic to jpg converter",
    "heic to png converter",
    "combine images to pdf",
    "batch image converter",
    "free image tools",
    "online pdf creator",
    "image format converter",
    "multiple images to pdf",
    "image processing online"
  ],
  authors: [
    {
      name: "sondoan17",
      url: "https://imgutils.xyz",
    },
  ],
};
